LOAD_ATTR operand changes in 3.12
zrax/pycdc pull request #424
Opened 2024-01-05 20:38 UTC by ncaklovic

See changes in [LOAD_ATTR](https://docs.python.org/3.12/library/dis.html#opcode-LOAD_ATTR)  for 3.12

2024-01-07 19:25 UTC, Mouad-scriptz approved these changes

2024-02-15 05:51 UTC, zrax requested changes

2024-02-15 05:51 UTC, zrax commented on bytecode.cpp
> +                    if (opcode == Pyc::LOAD_ATTR_A && mod->verCompare(3, 12) >= 0 && (arg & 1))
```suggestion
                    if (opcode == Pyc::LOAD_ATTR_A && mod->verCompare(3, 12) >= 0)
```
The shift in Python 3.12+ is unconditional (the flag stored at the lowest order bit is used independently of the name lookup)

2024-02-15 05:51 UTC, zrax commented on ASTree.cpp
> +                        arg >>= 1;
```suggestion
                    auto arg = (mod->verCompare(3, 12) >= 0) ? operand >> 1 : operand;
```

2024-02-28 23:44 UTC, merged